### PR TITLE
thd_engine_adapive: Change some struct field types

### LINKED ISSUE #284: Clang build issues
Not immediately sure how to properly fix these:

```
src/thd_engine_adaptive.cpp:428:42: error: result of comparison of constant 4096 with expression of type 'enum adaptive_condition' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
                        } else if (condition_set[j].condition >= 0x1000 && condition_set[j].condition < 0x10000) {
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~
src/thd_engine_adaptive.cpp:428:82: error: result of comparison of constant 65536 with expression of type 'enum adaptive_condition' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
                        } else if (condition_set[j].condition >= 0x1000 && condition_set[j].condition < 0x10000) {
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~
src/thd_engine_adaptive.cpp:440:36: error: result of comparison of constant 4 with expression of type 'enum adaptive_comparison' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
                        if (condition_set[j].comparison < ARRAY_SIZE(comp_strs)) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~
src/thd_engine_adaptive.cpp:876:29: error: result of comparison of constant 4 with expression of type 'enum adaptive_comparison' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
                        if (condition.comparison < ARRAY_SIZE(comp_strs)) {
                            ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

Are `condition` and `comparison` in `condition` really meant to be enums?

### PR DESCRIPTION
**Pull request by tbaederr**
The condition and comparison fields of the condition struct are used
for arbitrary integer values, not just the ones in their respective enum
fields. Reflect this by using an integer type and not an enum type.

This fixes the build with clang.

Fixes #284

I see there are tests in `tests/`, but I did not run any of them since I am not sure how.

### CODE REVIEW

File: src/thd_engine_adaptive.cpp [hunk 1]
```diff
@@ -846,7 +846,7 @@ int cthd_engine_adaptive::verify_condition(struct condition condition) {
 		return 0;
 
 	cond_name = condition_names[MIN(MAX(0, condition.condition), G_N_ELEMENTS(condition_names) - 1)];
-	thd_log_error("Unsupported condition %d (%s)\n", condition.condition, cond_name);
+	thd_log_error("Unsupported condition %lu (%s)\n", condition.condition, cond_name);
```
Comment (benzea) [inline src/thd_engine_adaptive.cpp:849]: Better use `%" PRIu64 "` instead of `%lu` to avoid issues/warnings as the definition of a `long int` depends on the platform.
